apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: product-service
  name: product-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  strategy: {}
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker
          image: prajwal/product-service
          imagePullPolicy: Never
          name: product-service
          ports:
            - containerPort: 8080  
          resources: {}
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: product-service
  name: product-service
  annotations:
    metallb.universe.tf/loadBalancerIPs: 172.16.2.140
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: product-service
  type: LoadBalancer
status:
  loadBalancer: {}

